# Generated by Django 5.0.6 on 2024-05-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSenai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
